server:
  port: 2333


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/neko
    username: sa
    password: 123456

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update